### ISSUE TITLE
Optional line of best fit

### ISSUE THREAD

**Issue by kjj207** [esantorella/binscatter#5]
Could there be an option passed in not to automatically overlay a line of best fit on the scatter plot

**Comment by esantorella** [comment]
@kjj207 Yes, I can do this by adding a parameter `fit_reg` like in [`seaborn.regplot`](https://seaborn.pydata.org/generated/seaborn.regplot.html) and [`seaborn.lmplot`](https://seaborn.pydata.org/generated/seaborn.lmplot.html#seaborn.lmplot). By the way, do either of those functions cover your use case? Seaborn is a good option if you don't need to account for any control variables.

**Comment by esantorella** [comment]
@kjj207 Closed by #6 ; let me know if you run into any issues.
